### ISSUE TITLE
Nat should coerce rather than just validate. But must still export a validator.

### ISSUE THREAD

**Issue by erights** [Agoric/nat#137]
See https://github.com/Agoric/agoric-sdk/pull/2209

Nat itself should be a coercer rather than a validator, so every call site I changed to Nat(BigInt(...)) can go back to Nat(...). However, validators are safer than coercers because they validate the input as well as the output. So @agoric/nat should also export a validator. And also an isNat predicate that returns false on invalid input rather than throwing.

**Comment by katelynsills** [comment]
Closed by #138
